// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using real_estate.Data;

#nullable disable

namespace real_estate.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231106164208_migation6oct")]
    partial class migation6oct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("real_estate.Models.Admin", b =>
                {
                    b.Property<int>("admin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("admin_id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("admin_id");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("real_estate.Models.Agreement", b =>
                {
                    b.Property<int>("agreement_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("agreement_id"));

                    b.Property<int>("admin_id")
                        .HasColumnType("int");

                    b.Property<string>("ag_type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("apartment_id")
                        .HasColumnType("int");

                    b.Property<int>("client_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("duration")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("payment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("agreement_id");

                    b.ToTable("agreement");
                });

            modelBuilder.Entity("real_estate.Models.Apartments", b =>
                {
                    b.Property<int>("apartment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("apartment_id"));

                    b.Property<int>("nu_room")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("property_Id")
                        .HasColumnType("int");

                    b.HasKey("apartment_id");

                    b.ToTable("apartments");
                });

            modelBuilder.Entity("real_estate.Models.Client", b =>
                {
                    b.Property<int>("client_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("client_id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("client_id");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("real_estate.Models.Features", b =>
                {
                    b.Property<int>("feature_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("feature_id"));

                    b.Property<string>("feature_descripition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("property_Id")
                        .HasColumnType("int");

                    b.HasKey("feature_id");

                    b.ToTable("features");
                });

            modelBuilder.Entity("real_estate.Models.Houses", b =>
                {
                    b.Property<int>("houses_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("houses_id"));

                    b.Property<int>("nu_room")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("property_Id")
                        .HasColumnType("int");

                    b.HasKey("houses_id");

                    b.ToTable("houses");
                });

            modelBuilder.Entity("real_estate.Models.Property", b =>
                {
                    b.Property<int>("property_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("property_Id"));

                    b.Property<int>("admin_id")
                        .HasColumnType("int");

                    b.Property<int>("client_Id")
                        .HasColumnType("int");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("p_type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("property_Id");

                    b.ToTable("property");
                });

            modelBuilder.Entity("real_estate.Models.Property_image", b =>
                {
                    b.Property<int>("pi_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pi_id"));

                    b.Property<string>("pi_image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("property_Id")
                        .HasColumnType("int");

                    b.HasKey("pi_id");

                    b.ToTable("property_image");
                });
#pragma warning restore 612, 618
        }
    }
}
